//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Wham
{
    [Serializable]
    public class ButtonlistMsg : Message
    {
        public const string k_RosMessageName = "wham/buttonlist";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public int[] buttons;

        public ButtonlistMsg()
        {
            this.header = new HeaderMsg();
            this.buttons = new int[16];
        }

        public ButtonlistMsg(HeaderMsg header, int[] buttons)
        {
            this.header = header;
            this.buttons = buttons;
        }

        public static ButtonlistMsg Deserialize(MessageDeserializer deserializer) => new ButtonlistMsg(deserializer);

        private ButtonlistMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.buttons, sizeof(int), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.buttons);
        }

        public override string ToString()
        {
            return "ButtonlistMsg: " +
            "\nheader: " + header.ToString() +
            "\nbuttons: " + System.String.Join(", ", buttons.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
